# Generated by Django 3.2 on 2022-01-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_masterakuncoa'),
        ('kertaskerja', '0003_auto_20211230_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('penanggung_jawab_kegiatan', models.CharField(max_length=100)),
                ('anggaran_biaya', models.IntegerField()),
                ('akuncoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.masterakuncoa')),
                ('sasaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kertaskerja.daftarsasaran')),
            ],
        ),
    ]
